# This container runs `fixcore`.
ARG IMAGE_TAG=edge
FROM ghcr.io/someengineering/fixinventorybase:${IMAGE_TAG}
EXPOSE 8900
ENTRYPOINT ["/bin/dumb-init", "--", "/usr/local/sbin/bootstrap", "/usr/bin/fixcore"]
