# This container runs `fixmetrics`.
ARG IMAGE_TAG=edge
FROM ghcr.io/someengineering/fixinventorybase:${IMAGE_TAG}
EXPOSE 9955
ENTRYPOINT ["/bin/dumb-init", "--", "/usr/local/sbin/bootstrap", "/usr/bin/fixmetrics"]
