# This container runs `resotoworker`.
ARG IMAGE_TAG=edge
FROM ghcr.io/someengineering/resotobase:${IMAGE_TAG}
EXPOSE 9956
ENTRYPOINT ["/bin/dumb-init", "--", "/usr/local/sbin/bootstrap", "/usr/bin/resotoworker"]
