{
 "title": "Cloudkeeper - Quotas",
 "tags": [
  "cloudkeeper",
  "instances",
  "volumes",
  "quotas"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(cloudkeeper_instances_total,cloud)"
   },
   {
    "name": "account",
    "label": "Account",
    "query": "label_values(cloudkeeper_instances_total,account)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(cloudkeeper_instances_total,region)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances quotas",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(avg_over_time(cloudkeeper_instances_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"running\"}[$__interval])) by (cloud, account, region, type))",
     "legendFormat": "running"
    },
    {
     "expr": "sum(avg_over_time(cloudkeeper_instances_quotas_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud, account, region, type)",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "Volumes quotas (TiB)",
   "type": "table",
   "description": "Quota is the value for the provisioned volumes size in Tebibyte",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sort_desc(sum(avg_over_time(cloudkeeper_volume_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])/1024/1024/1024) by (cloud, account, region, type))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg_over_time(cloudkeeper_volumes_quotas_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])/1024/1024/1024) by (cloud, account, region, type)",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "Loadbalancers quotas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc(sum(avg_over_time(cloudkeeper_load_balancers_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud, account, region, type))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg_over_time(cloudkeeper_load_balancers_quotas_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud, account, region, type)",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "Gateways quotas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sort_desc(sum(avg_over_time(cloudkeeper_gateways_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud, account, region, type))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg_over_time(cloudkeeper_gateways_quotas_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud, account, region, type)",
     "legendFormat": "quota"
    }
   ]
  }
 ]
}