{
 "title": "fix - Age",
 "tags": [
  "fix",
  "volumes",
  "buckets",
  "network"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cloud", "label": "Cloud", "query": "label_values(cloud)" },
   {
    "name": "account",
    "label": "Account",
    "query": "label_values(fix_instances_total, account)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(fix_instances_total, region)"
   },
   {
    "name": "instance_status",
    "label": "Instance Status",
    "query": "label_values(fix_instances_total,status)"
   },
   {
    "name": "volumes_status",
    "label": "Volumes Status",
    "query": "label_values(fix_volumes_total,status)"
   },
   {
    "name": "volume_types",
    "label": "Volume Type",
    "query": "label_values(fix_volumes_total,type)"
   },
   {
    "name": "age",
    "label": "Age",
    "query": "label_values(fix_instances_age_range,age)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances Age",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_instances_age_range{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$instance_status\",age=~\"$age\"}[$__interval])) by (cloud,account,age)",
     "legendFormat": "{{cloud}} {{account}} {{age}}"
    }
   ]
  },
  {
   "title": "Instances Age Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_instances_age_range{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$instance_status\",age=~\"$age\"}[$__interval])) by (age)",
     "legendFormat": "{{age}}"
    }
   ]
  },
  {
   "title": "Volumes Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_volumes_age_range{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$volumes_status\",age=~\"$age\"}[$__interval])) by (cloud,account,age)",
     "legendFormat": "{{cloud}} {{account}} {{age}}"
    }
   ]
  },
  {
   "title": "Volumes Age Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_volumes_age_range{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$volumes_status\",age=~\"$age\"}[$__interval])) by (age)",
     "legendFormat": "{{age}}"
    }
   ]
  }
 ]
}