{
 "title": "fix - IAM",
 "description": "See users, roles, accounts, etc",
 "tags": [
  "fix",
  "iam",
  "users",
  "roles",
  "accounts",
  "policies",
  "groups",
  "profiles"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cloud", "label": "Cloud", "query": "label_values(cloud)" },
   { "name": "account", "label": "Account", "query": "label_values(account)" },
   { "name": "region", "label": "Region", "query": "label_values(region)" }
  ]
 },
 "panels": [
  {
   "title": "Users total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_users_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Groups total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_groups_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Roles total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_roles_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Access keys total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_access_keys_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Instance profiles total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_instance_profiles_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Policies total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fix_policies_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  }
 ]
}