{
 "title": "resoto - Application",
 "description": "Information about the resoto application",
 "tags": [
  "resoto",
  "stats"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "aws_collect",
   "type": "graph",
   "description": "Time it took the collect() method",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_seconds_sum[60m])/rate(resoto_plugin_aws_collect_seconds_count[60m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(process_virtual_memory_bytes{job=\"resoto\"}[$__interval])/1024/1024)",
     "legendFormat": "virtual"
    },
    {
     "expr": "sum(avg_over_time(process_resident_memory_bytes{job=\"resoto\"}[$__interval])/1024/1024)",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"resoto\"}[60m]))",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "aws_collect_*",
   "type": "graph",
   "description": "Time it took the collect_*() method",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_vpcs_seconds_sum[60m])/rate(resoto_plugin_aws_collect_subnets_seconds_count[60m]))",
     "legendFormat": "vpcs"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_vpcs_seconds_sum[60m])/rate(resoto_plugin_aws_collect_subnets_seconds_count[60m]))",
     "legendFormat": "subnets"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_route_tables_seconds_sum[60m])/rate(resoto_plugin_aws_collect_route_tables_seconds_count[60m]))",
     "legendFormat": "route_tables"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_security_groups_seconds_sum[60m])/rate(resoto_plugin_aws_collect_security_groups_seconds_count[60m]))",
     "legendFormat": "security_groups"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_internet_gateways_seconds_sum[60m])/rate(resoto_plugin_aws_collect_internet_gateways_seconds_count[60m]))",
     "legendFormat": "internet_gateways"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_instances_seconds_sum[60m])/rate(resoto_plugin_aws_collect_instances_seconds_count[60m]))",
     "legendFormat": "instances"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_volumes_seconds_sum[60m])/rate(resoto_plugin_aws_collect_volumes_seconds_count[60m]))",
     "legendFormat": "volumes"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_network_interfaces_seconds_sum[60m])/rate(resoto_plugin_aws_collect_network_interfaces_seconds_count[60m]))",
     "legendFormat": "network_interfaces"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_buckets_seconds_sum[60m])/rate(resoto_plugin_aws_collect_buckets_seconds_count[60m]))",
     "legendFormat": "buckets"
    },
    {
     "expr": "avg(rate(resoto_plugin_aws_collect_elbs_seconds_sum[60m])/rate(resoto_plugin_aws_collect_elbs_seconds_count[60m]))",
     "legendFormat": "elbs"
    }
   ]
  },
  {
   "title": "search",
   "type": "graph",
   "description": "Time it took the Graph search() method",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resoto_graph_search_seconds_sum[60m])/rate(resoto_graph_search_seconds_count[60m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "search_first",
   "type": "graph",
   "description": "Time it took the Graph search_first() method",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resoto_graph_search_first_seconds_sum[60m])/rate(resoto_graph_search_first_seconds_count[60m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "open_fds",
   "type": "graph",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(sum_over_time(process_open_fds{job=\"resoto\"}[$__interval]))",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "container_cache_update",
   "type": "graph",
   "description": "Time it took the GraphContainer update_caches() method",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resoto_graph_container_cache_update_sum[60m])/rate(resoto_graph_container_cache_update_count[60m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "search_first_parent_class",
   "type": "graph",
   "description": "Time it took the Graph search_first_parent_class() method",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resoto_graph_search_first_parent_seconds_sum[60m])/rate(resoto_graph_search_first_parent_seconds_count[60m]))",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}