{
 "title": "resoto - Overview",
 "tags": [
  "resoto",
  "instances",
  "cores",
  "memory",
  "cost estimate"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(resoto_instances_total, cloud)"
   },
   {
    "name": "account",
    "label": "Account",
    "query": "label_values(resoto_instances_total, account)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(resoto_instances_total, region)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances $cloud - running",
   "type": "singlestat",
   "description": "current value",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"running\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Cloud $cloud - Volumes",
   "type": "singlestat",
   "description": "current value",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volumes_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Cloud $cloud - not used Volumes",
   "type": "singlestat",
   "description": "current value",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volumes_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"available\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Instances $cloud - Memory",
   "type": "singlestat",
   "description": "current value",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_memory_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval]))/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Instances $cloud - Cost estimate",
   "type": "singlestat",
   "description": "current value",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_hourly_cost_estimate{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Volumes $cloud - Cost estimate",
   "type": "singlestat",
   "description": "current value",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volumes_monthly_cost_estimate{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Instances total - running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"running\"}[$__interval])) by (cloud,account)",
     "legendFormat": "{{cloud}} {{account}}"
    }
   ]
  },
  {
   "title": "Instances - Cost estimate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Amount / hour" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_hourly_cost_estimate{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,account)",
     "legendFormat": "{{cloud}} {{account}}"
    }
   ]
  },
  {
   "title": "Volumes total + available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volumes_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"in-use\"}[$__interval])) by (cloud,account)",
     "legendFormat": "{{cloud}} {{account}}"
    },
    {
     "expr": "sum(sum(avg_over_time(resoto_volumes_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"available\"}[$__interval])) by (cloud,account))",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Volumes bytes used + available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "gbytes", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volume_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"in-use\"}[$__interval])/1024/1024/1024) by (cloud,account)",
     "legendFormat": "{{cloud}} {{account}}"
    },
    {
     "expr": "sum(sum(avg_over_time(resoto_volume_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"available\"}[$__interval])/1024/1024/1024) by (cloud,account))",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Volumes - Costs estimate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Amount / month" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volumes_monthly_cost_estimate{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"in-use\"}[$__interval])) by (cloud,account)",
     "legendFormat": "{{cloud}} {{account}}"
    },
    {
     "expr": "sum(sum(avg_over_time(resoto_volumes_monthly_cost_estimate{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"available\"}[$__interval])) by (cloud,account))",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Instances total - running",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=\"running\"}[$__interval])) by (cloud, type)",
     "legendFormat": "{{cloud}} - {{type}}"
    }
   ]
  },
  {
   "title": "Cores total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_cores_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud, account)",
     "legendFormat": "{{cloud}} {{account}}"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "gbytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "sum((avg_over_time(resoto_memory_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])/1024/1024/1024)) by (cloud, account)",
     "legendFormat": "{{cloud}} {{account}}"
    }
   ]
  }
 ]
}