{
 "title": "resoto - Details",
 "tags": [
  "resoto",
  "volumes",
  "buckets",
  "network"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cloud",
    "label": "Cloud",
    "query": "label_values(resoto_instances_total,cloud)"
   },
   {
    "name": "account",
    "label": "Account",
    "query": "label_values(resoto_instances_total,account)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(resoto_instances_total,region)"
   },
   {
    "name": "instance_status",
    "label": "Instance Status",
    "query": "label_values(resoto_instances_total,status)"
   },
   {
    "name": "volumes_status",
    "label": "Volumes Status",
    "query": "label_values(resoto_volumes_total,status)"
   },
   {
    "name": "volume_types",
    "label": "Volume Type",
    "query": "label_values(resoto_volumes_total,type)"
   },
   {
    "name": "network_interfaces_status",
    "label": "Network Interface Status",
    "query": "label_values(resoto_network_interfaces_total,status)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$instance_status\"}[$__interval])) by (cloud,region,account,type)",
     "legendFormat": "{{cloud}} {{account}} {{region}} {{type}}"
    }
   ]
  },
  {
   "title": "Instances - Cost estimate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Amount / hour" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_hourly_cost_estimate{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", region=~\"$region\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Instances total",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_instances_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$instance_status\"}[$__interval])) by (cloud, type)",
     "legendFormat": "{{cloud}} - {{type}}"
    }
   ]
  },
  {
   "title": "Volumes total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_volumes_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", type=~\"$volume_types\", status=~\"$volumes_status\"}[$__interval])) by (cloud,region,account,type,status)",
     "legendFormat": "{{cloud}} {{account}} {{region}} {{type}} {{status}}"
    }
   ]
  },
  {
   "title": "Volumes Size total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "gbytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "sum((avg_over_time(resoto_volume_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", type=~\"$volume_types\", status=~\"$volumes_status\"}[$__interval])/1024/1024/1024)) by (cloud,region,account,type,status)",
     "legendFormat": "{{cloud}} {{account}} {{region}} {{type}} {{status}}"
    }
   ]
  },
  {
   "title": "Databases total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_databases_total{cloud=~\"$cloud\", account=~\"$account\"}[$__interval])) by (cloud,account,type,instance_type)",
     "legendFormat": "{{cloud}} {{account}} - {{instance_type}} - {{type}} "
    }
   ]
  },
  {
   "title": "Database bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "gbytes", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_databases_bytes{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])/1024/1024/1024) by (cloud,account,type,instance_type)",
     "legendFormat": "{{cloud}} {{account}} - {{instance_type}} - {{type}} "
    }
   ]
  },
  {
   "title": "Subnets total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_subnets_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Buckets total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_buckets_total{cloud=~\"$cloud\", account=~\"$account\"}[$__interval])) by (cloud,account)",
     "legendFormat": "{{cloud}} {{account}}"
    }
   ]
  },
  {
   "title": "Loadbalancers total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_load_balancers_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Security groups total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_security_groups_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Network interfaces total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_network_interfaces_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\", status=~\"$network_interfaces_status\"}[$__interval])) by (cloud,region,account,status)",
     "legendFormat": "{{cloud}} {{account}} {{region}} {{status}}"
    }
   ]
  },
  {
   "title": "Networks total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_networks_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  },
  {
   "title": "Routing tables total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(resoto_routing_tables_total{cloud=~\"$cloud\", region=~\"$region\", account=~\"$account\"}[$__interval])) by (cloud,region,account)",
     "legendFormat": "{{cloud}} {{account}} {{region}}"
    }
   ]
  }
 ]
}