blank_issues_enabled: false
contact_links:
  - name: 💬 Discord
    url: https://discord.gg/XvpyRQ4yj2
    about: Chat with other users and the development team
  - name: 📄 Documentation
    url: https://inventory.fix.security/docs
    about: Read and search documentation
