name: ✨ Feature Request
description: Suggest an idea
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please provide a clear and concise description of the rationale behind this request.
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired Behavior
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
  - type: markdown
    attributes:
      value: |
        By submitting this bug report, you agree to follow our [Code of Conduct](https://github.com/someengineering/resoto/blob/main/CODE_OF_CONDUCT.md).
