#!/bin/bash
set -euo pipefail
. /usr/local/etc/resoto/defaults
. /usr/local/etc/resoto/common

is_up=false

while [ $is_up = false ]; do
    echo "Waiting for GraphDB to start up"
    sleep 1
    if arangosh \
        --console.history false \
        --server.password "$GRAPHDB_ROOT_PASSWORD" \
        --javascript.execute-string "db._version()" > /dev/null 2>&1
    then
        is_up=true
    fi
done

echo "Creating $RESOTOCORE_GRAPHDB_USERNAME user and $RESOTOCORE_GRAPHDB_DATABASE database if they do not yet exist."
cat <<EOF | arangosh --console.history false --server.password "$GRAPHDB_ROOT_PASSWORD" > /dev/null 2>&1
const users = require('@arangodb/users');
users.save('$RESOTOCORE_GRAPHDB_USERNAME', '$RESOTOCORE_GRAPHDB_PASSWORD');
db._createDatabase('$RESOTOCORE_GRAPHDB_DATABASE');
users.grantDatabase('$RESOTOCORE_GRAPHDB_USERNAME', '$RESOTOCORE_GRAPHDB_DATABASE', 'rw');
EOF
