#!/bin/bash
set -euo pipefail
. /usr/local/etc/cloudkeeper/defaults
. /usr/local/etc/cloudkeeper/common

is_up=false

while [ $is_up = false ]; do
    echo "Waiting for GraphDB to start up"
    sleep 1
    if arangosh \
        --console.history false \
        --server.password "$GRAPHDB_ROOT_PASSWORD" \
        --javascript.execute-string "db._version()" > /dev/null 2>&1
    then
        is_up=true
    fi
done

echo "Creating $CKCORE_GRAPHDB_LOGIN user and $CKCORE_GRAPHDB_DATABASE database"
cat <<EOF | arangosh --console.history false --server.password "$GRAPHDB_ROOT_PASSWORD" > /dev/null 2>&1
const users = require('@arangodb/users');
users.save('$CKCORE_GRAPHDB_LOGIN', '$CKCORE_GRAPHDB_PASSWORD');
db._createDatabase('$CKCORE_GRAPHDB_DATABASE');
users.grantDatabase('$CKCORE_GRAPHDB_LOGIN', '$CKCORE_GRAPHDB_DATABASE', 'rw');
EOF
