extends Node

signal go_to_graph_node
signal load_query
signal graph_spaceship
signal graph_randomize
signal graph_order
signal nodeinfo_show
signal nodeinfo_hide
signal nodes_changed
signal load_nodes
signal show_blastradius
signal msg
signal loading
signal loading_done
signal loading_start
signal create_jwt
signal connect_popup
signal api_connect
signal api_request
signal change_cam_zoom
