#!/bin/bash
. /usr/local/etc/fixinventory/defaults
. /usr/local/fix-venv-python3/bin/activate
export RESOTOSHELL_PSK
export RESOTOSHELL_RESOTOCORE_URI

if [ "$1" = "--wait" ]; then
    exec /usr/local/bin/fixsh-wait
else
    exec fixsh --resotocore-wait 300 "$@"
fi
