#!/bin/bash
. /usr/local/etc/resoto/defaults
. /usr/local/resoto-venv-python3/bin/activate
export RESOTOSHELL_PSK
export RESOTOSHELL_RESOTOCORE_URI

if [ "$1" = "--wait" ]; then
    exec /usr/local/bin/resh-wait
else
    exec resh --resotocore-wait 300 "$@"
fi
