#!/bin/bash
. /usr/local/etc/resoto/defaults
. /usr/local/resoto-venv-python3/bin/activate
export RESOTOWORKER_PSK
export RESOTOWORKER_RESOTOCORE_URI
export RESOTOWORKER_RESOTOCORE_WS_URI
exec resotoworker "$@"
