name: Lint (fixcore)
on:
  push:
    branches:
      - main
    paths:
      - 'fixcore/**'
      - '.github/**'
      - 'requirements-all.txt'
  pull_request:
    paths:
      - 'fixcore/**'
      - '.github/**'
      - 'requirements-all.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  fixcore-lint:
    name: "Lint (fixcore)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Restore dependency cache
        uses: actions/cache@v4
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{runner.os}}-pip-${{hashFiles('./fixcore/pyproject.toml')}}-${{hashFiles('./fixcore/requirements-all.txt')}}
      - name: Install Dependencies
        run: ./setup_venv.sh --dev --no-venv --no-plugins
      - name: Check Formatting
        working-directory: ./fixcore
        run: black --line-length 120 --check fixcore tests
      - name: Lint
        working-directory: ./fixcore
        run: |
          flake8 fixcore
          pylint fixcore
      - name: MyPy
        working-directory: ./fixcore
        run: mypy --install-types --non-interactive --strict fixcore tests
